version: '3'
services:
  app:
    container_name: go-persistor
    image: go-persistor:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: predictions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
  db:
    container_name: predictions-database
    image: postgres:latest
    environment:
      POSTGRES_DB: predictions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge

